# All our tasty lil authorization tokens
[authorization_tokens]
    bot = "bot_token"
    paypal = ""
    topgg = ""

# This data is passed directly over to asyncpg
[database]
    user = "database_username"
    password = "database_password"
    database = "database_name"
    host = "127.0.0.1"
    port = 5432
    enabled = false

# This data is passed directly over to aioredis
[redis]
    host = "127.0.0.1"
    port = 6379
    db = 0
    enabled = false

# Used for Discord login data
[oauth]
    client_id = ""
    client_secret = ""
